### ISSUE TITLE
Update TARDIS setup and package infrastructure

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1216]
TARDIS's setup and package architecture is based on the`astropy`'s excellent package template ( https://github.com/astropy/package-template) this has changed in the last years and we should update our infrastructure to follow the new guidelines. We should also look out for this https://github.com/astropy/astropy-APEs/blob/master/APE17.rst. Once things are changed we need to add these files to be excluded from codestyle black changes.

**Comment by epassaro** [comment]
Some considerations:

- Maybe would be nice to implement it before on `carsus` since it's a smaller package to learn how it works
- `tardis` still have montecarlo Cython code included (is this the only compiled extension, right?). Would be nice to ditch this before moving to new `astropy` template
- Moving to new template should be done before moving on `conda-forge` (or any form of packaging) otherwise we will doing the same job twice

**Comment by epassaro** [comment]
Already moved `carsus` to the new package infrastructure, this could be done soon.

**Comment by epassaro** [comment]
Closed by #1674
