### ISSUE TITLE
Twitter feed on docs page to replace News section

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#1545]
**Is your feature request related to a problem? Please describe.**
Currently, the News part of the documentation is extremely outdated because it is hard to update (requires a PR).

**Describe the solution you'd like**
A feed of the TARDIS-SN twitter output https://twitter.com/tardis_sn because it is updated more regularly

**Describe alternatives you've considered**
Some kind of external input to the News section that is not required to go via a pull request

**Comment by antreev-brar** [comment]
This is really interesting. Integration of Twitter feed into the documentation would give it a dynamic look as well.

**Comment by jaladh-singhal** [comment]
Thanks, Andrew - I was about to create this issue. This explains how to do
it:
https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview

**Comment by atharva-2001** [comment]
Thanks, @jaladh-singhal for the information!
Replacing previous text with this code block does the trick:
```rst
.. raw:: html
    
    <embed >
    <a class="twitter-timeline" data-width="550" data-height="900" href="https://twitter.com/tardis_sn?ref_src=twsrc%5Etfw">Tweets by tardis_sn</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </embed>
```

Something like this: 
![image](https://user-images.githubusercontent.com/55894364/115956444-517fe100-a51a-11eb-8afb-490614c9eae5.png)

See the live version [here](https://atharva-2001.github.io/tardis/)
Should I make a PR on this?

**Comment by antreev-brar** [comment]
@atharva-2001 Looks good

**Comment by jaladh-singhal** [comment]
>  Replacing previous text with this code block does the trick
Exactly this is how it was supposed to be done - well done @atharva-2001!

> Something like this:
This looks great. I have few questions/suggestions:
1. Make the News title of same heading level as that of Mission Statememt
2. Why doesn't this embedded timeline show our latest Apr 21 tweet?
3. Can you increase width of this a bit - it looks pretty narrow on desktop. Also I wonder if it will look better on centre aligning this instead of left aligning? (This will require some hit & trial, can you post screenshots of multiple options if you have time to try them - then we can choose one?)

>  Should I make a PR on this?
Definitely - there's no need to ask & thanks a lot for taking up charge on this! :)

**Comment by Molkree** [comment]
> 2\. Why doesn't this embedded timeline show our latest Apr 21 tweet?

Just checked Twitter [page](https://twitter.com/tardis_sn), this is kinda weird because it's not being displayed on the Twitter site too under "Tweets" tab, I can only see it under "Tweets & replies" tab. But it's not a reply???

Not shown in "Tweets" tab
![image](https://user-images.githubusercontent.com/12860284/115967407-26f25000-a53b-11eb-9747-65da5b23ecb2.png)

Shown in "Tweets & replies" tab
![image](https://user-images.githubusercontent.com/12860284/115967415-2eb1f480-a53b-11eb-846c-971b7d4fca50.png)

**Comment by jaladh-singhal** [comment]
@Molkree that's super weird. Because I can see it in both logged-in and incognito mode:

![image](https://user-images.githubusercontent.com/36361463/115967623-4a27fa00-a551-11eb-9089-b8b68e9bbe84.png)

@atharva-2001 can you see it?

**Comment by Molkree** [comment]
Aha, I see. That must be some kind of Twitter caching/CDN issue, I changed to USA VPN and I can see April 21 tweet on the main page too. Probably nothing we can do and should just wait and/or report it to Twitter.

**Comment by atharva-2001** [comment]
> Exactly this is how it was supposed to be done - well done @atharva-2001!

Thank you so much!

> This looks great. I have few questions/suggestions:
> 
> 1. Make the News title of same heading level as that of Mission Statememt
> 2. Why doesn't this embedded timeline show our latest Apr 21 tweet?
> 3. Can you increase width of this a bit - it looks pretty narrow on desktop. Also I wonder if it will look better on centre aligning this instead of left aligning? (This will require some hit & trial, can you post screenshots of multiple options if you have time to try them - then we can choose one?)


I added some JS to (change the CSS and) improve the appearance. 

```rst
.. raw:: html

    <div class = "twitter-block"  style = "width:100%; display: flex; justify-content: center;">
    <a class="twitter-timeline" data-width="850" data-height="900" href="https://twitter.com/tardis_sn?ref_src=twsrc%5Etfw">Tweets by tardis_sn</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>



    <script>
    jQuery('.twitter-block').delegate('#twitter-widget-0','DOMSubtreeModified propertychange', function() {
    //function call to override the base twitter styles
    customizeTweetMedia();
    });

    var customizeTweetMedia = function() {
        //overrides css 
        jQuery('.twitter-block').find('.twitter-timeline').contents().find('.timeline-Header-title.u-inlineBlock').css('font-size', '18px');
        jQuery('.twitter-block').find('.twitter-timeline').contents().find('.timeline-Header-title.u-inlineBlock').children().css('font-size', '18px');
        jQuery('.twitter-block').find('.twitter-timeline').contents().find('.timeline-Tweet-text').css({'font-size': '16px', 'font': 'Lato,proxima-nova,Helvetica Neue,Arial,sans-serif;', 'line-height': '1.1'});

        //also call the function on dynamic updates in addition to page load
        jQuery('.twitter-block').find('.twitter-timeline').contents().find('.timeline-TweetList').bind('DOMSubtreeModified propertychange', function() {
        customizeTweetMedia(this);
        });
    }
    </script>
```

The `customizeTweetMedia` function and other JS code is a modified version of this code [here](https://fjorgedigital.com/insights/blog/can-i-add-custom-styles-to-my-embedded-twitter-timeline/)

I changed the CSS of the widget because the widget font size would increase if I increased the width of the widget and that used to look out of proportion to the rest of the text. 
Before changing CSS:
![image](https://user-images.githubusercontent.com/55894364/115994769-f28f9a00-a5f5-11eb-8d12-fe57bd8b9294.png)

After changing CSS: 
![image](https://user-images.githubusercontent.com/55894364/115994849-5dd96c00-a5f6-11eb-8044-cf9554254bf5.png)

This is how it looks if I do not centre the widget and align it to the left: 
![image](https://user-images.githubusercontent.com/55894364/115995028-2e772f00-a5f7-11eb-8b76-4c661e8adef6.png)

The live version [here](https://atharva-2001.github.io/tardis/) has the widget centred. 

> Why doesn't this embedded timeline show our latest Apr 21 tweet?

I too haven't figured this out yet. Maybe [this link](https://stackoverflow.com/a/35305401/11974464
) might help us. The above screenshots are taken almost around the same time. Still, sometimes it's visible and sometimes it's not. 

> @atharva-2001 can you see it?

Yes, I can on the Twitter website. But I *can't always* in the widget.

> Aha, I see. That must be some kind of Twitter caching/CDN issue, I've switched to USA VPN and I can see April 21 tweet on the main page too. Probably nothing we can do and should just wait and/or report it to Twitter.

This could be possible. I  will try to see if I can find something and maybe we can report it to the [Twitter community](https://twittercommunity.com/). 

> Definitely - there's no need to ask & thanks a lot for taking up charge on this! :)

Thank you! Please let me know where I can improve and I will make a PR as soon as possible.
