### ISSUE TITLE
Add option to specify input luminosity in config file (rather output)

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#166]
As requested by Ken Shen, we should provide an option in the configuration file in the "supernova" section that the "luminosity_requested" is not the emergent luminosity but rather the input luminosity - might be of value for theory-oriented work.

Should be easy to add: just means that the config needs to understand it and then during the iteration cycle we always insist on the input number being used (rather than modifying it to try and match the emerging luminosity).

**Comment by unoebauer** [comment]
@ssim, @wkerzendorf: I guess this one is still relevant, despite the lack of activity. However, with the simulation restructure and the new Dalek fitting strategy (treating T_inner as a parameter which is kept fixed during the iterations), we basically have such a feature ready: specify T_inner, the velocity of the innermost cell and the time since explosion and we have a fixed input luminosity during the iteration cycles. What do you think, can we close this one?

**Comment by wkerzendorf** [comment]
It's missing the ability to set this in the config file.  - so for now can we leave this open?

**Comment by unoebauer** [comment]
Fine with me - leaving this one open

**Comment by unoebauer** [comment]
In fact, this is already possible (albeit not very intuitive) by specifying  ``T_inner`` and by setting ``hold_iterations``. Together with the photospheric velocity and the time since explosion, this specifies a constant input luminosity.

Feature request fulfilled - closing :)
