### ISSUE TITLE
Profiling of TARDIS information location

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1663]
It is not a `Profile` of TARDIS. The name is profiling (not sure what the output is called). I also think it should live under development, right?

**Comment by KevinCawley** [comment]
Right now it lives under I/O, and it will move to Tutorials once that section is made, as it is a basic tutorial of how to profile TARDIS. That is the plan right now.

**Comment by wkerzendorf** [comment]
I think developing is a better place. Tutorial is more of user tutorials - @smithis7 what do you think?

**Comment by smithis7** [comment]
@wkerzendorf I'll take responsibility for that -- the placement under io/output was my idea. I thought it would be very temporary but as I am having those issues with binder, the tutorials section may not be there for a little bit.

I do agree with you, I think the notebook should be under development. @KevinCawley I can make that change though since putting it under io/output was my idea.

**Comment by wkerzendorf** [comment]
thanks to both 😄
