### ISSUE TITLE
[discussion] replace `python setup.py ...` with `pip` ?

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/tardis#1690]
**Description:**

After merging #1686 `pip` install will be available again. I think `pip install .` catches more errors than `python setup.py install` making our code a bit more robust.

**NOTE:**
`pip install -e .` is equivalent to `python setup.py develop`.

Opinions?

**Comment by DhruvSondhi** [comment]
It would be a very welcoming change 😄. It is better that we have `pip install abc` as it is more in sync with something like `conda install xyz`. Plus, as we are going to remove the `python setup.py --args` it will be much easier for someone, who hasn't read the documentation or doesn't understand the `setup.py` architecture for installation or development, to install the package as it is instinctive that we try `conda install` or `pip install` rather than `python setup.py --args`.
