### ISSUE TITLE
Changelog workflow is broken

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#1871]
**Describe the bug**

Changelog workflow is refusing to push, claiming that it hasn't got a branch checked out.

**To Reproduce**

Run changelog workflow

**Screenshots**

![image](https://user-images.githubusercontent.com/20341051/150811378-71cbe504-4baa-40b2-9ec6-790d5d2ecf7f.png)

**Comment by madoyi** [comment]
I'd like to help out with this issue, is there a specific implementation you had in mind ?

**Comment by rohithvarma3000** [comment]
Hey, I have been exploring this issue for a day. https://github.com/actions/checkout/issues/124#issuecomment-584264556 This comment explains the reason why this issue arises. I think a push to a PR related branch is also considered as a trigger. So we need to do some study regarding when this workflow should be called.

The simplest way to fix the issue will be through a `git checkout` and then performing the push.

Also I had a suggestion. I think we need to setup a conditional statement to prevent the workflow from running in forks of the repository. This is because the fork will not have the `BOT_TOKEN` secret and the workflow may give an error.

I would love to work on this issue as well.

**Comment by rohithvarma3000** [comment]
I have a made a mistake in my previous comment. The workflow is being triggered correctly and the PR is not causing the error. The detached head occurs due to the way git handles tags. When we make a commit over the tag, the commit is not attached to any branch. The tag still points to the previous commit. So we need to modify the tag accordingly to handle this change.

**Comment by epassaro** [comment]
Replaced by the pre-release workflow. 

Closing.
