### ISSUE TITLE
Tardis not working with Artis files properly.

### ISSUE THREAD

**Issue by aoifeboyle** [tardis-sn/tardis#290]
Tardis gets confused when I give it an artis-style model and abundances file. There seems to be some kind of mismatch between the number of zones it identifies from the two files. The error I get specifically is this, from line 1058 of config_reader.py:

‘Wrong number of items passed 80, placement implies 79’

I made a couple of changes to model.py, where the file data is read in, but that just led to other errors. The abundances and model files I have been using are here: 

https://db.tt/KiIw8jfk

Thanks for any help! Aoife

**Comment by ssim** [comment]
@aoifeboyle Hi Aoife - can you also post the .yml file that you are working with?

**Comment by aoifeboyle** [comment]
@ssim I've just added it to the dropbox folder linked above :)

**Comment by ssim** [comment]
Some progress. I think that part of the issue is that someone has changed the way that the velocity boundaries are specified: rather than velocity start and stop values, I seem to get something to work with v_inner_boundary and v_outer_boundary. @mklauser @wkerzendorf can one of you confirm that this has changed - or is there meant to be another way to do this? 

@aoifeboyle Try something like this yml file (but notice that all my ionization approximations etc. are not what you want):

---
#Currently only simple1d is allowed
tardis_config_version: v1.0
supernova:
    luminosity_requested: 9.44 log_lsun
    time_explosion: 13 day
    distance : 24.2 Mpc


atom_data: kurucz_cd23_chianti_H_He.h5


model:
        
    
    structure:
        type: file
        filename: HM_Model.txt
        filetype: artis 
        v_inner_boundary: 8400 km/s
        v_outer_boundary: 30000 km/s
            
    abundances:
        type: file
        filename: HM_Abundances.txt
        filetype: artis
                
plasma:
    ionization: lte
    excitation: lte
    radiative_rates_type: dilute-blackbody
    line_interaction_type: scatter

montecarlo:
    seed: 23111963
    no_of_packets : 4.0e+4
    iterations: 20
    
    black_body_sampling:
        start: 1 angstrom
        stop: 1000000 angstrom
        num: 1.e+6
    last_no_of_packets: 1.e+5
    no_of_virtual_packets: 10

    convergence_criteria:
        type: specific
        damping_constant: 1.0
        threshold: 0.05
        fraction: 0.8
        hold: 3
        t_inner:
            damping_constant: 1.0
    

spectrum:
    start : 500 angstrom
    stop : 20000 angstrom
    num: 10000

**Comment by ssim** [comment]
However, there is still some sort of underlying issue here: even without specified boundary velocities the code should run and I agree that it currently doesn't. 

@aoifeboyle Can you check that the zones are lining up properly with a model - i.e. that the abundance / density patterns that Tardis ends up with are correct (and not that e.g. the abundances are all offset by 1 zone or something)

Another note: it doesn't work if you put the boundary velocity exactly on a real grid cell boundary. So e.g. 8250 km/s exactly causes problems because that's where there's a zone boundary in the model. This is also something that should be sorted at some point, but it's not too important so long as we are all aware.

**Comment by aoifeboyle** [comment]
@ssim Ok, I originally had my velocities specified like this (which I got from an example config. with the latest version of Tardis I downloaded): 
    structure:
        type: file
        filename: HM_Model.txt
        filetype: artis 
        velocity:
            start : 8500 km/s
            stop : 28000 km/s  
When I change it to 'v_inner_boundary' and 'v_outer_boundary' as you have above, that seems to work. Which seems weird but I'm ok with it if I can be sure it works.

I know that with the original error, the function for reading the abundances in in model_reader.py was skipping the first row.So I changed: 

    index = data[1:,0].astype(int)
    abundances = pd.DataFrame(data[1:,1:].transpose(), index=np.arange(1, data.shape[1]))

to:

    index = data[0:,0].astype(int)
    abundances = pd.DataFrame(data[0:,1:].transpose(), index=np.arange(1, data.shape[1]))

But that just generates another error from config_reader.py: 'The abundance file specified has not the same number of cells as the specified density profile.' So then I changed the way the number of shells was calculated, but that created another error, etc. so eventually I stopped.

I checked to see if the config_reader was reading in the files correctly with the velocity boundaries specified by v_inner_boundary and v_outer_boundary, and it seems to. At least, the values from the abundance files match up correctly to those of the zone outer velocities from the model structure file. 

So should I just go ahead and use v_inner_boundary and v_outer_boundary?

**Comment by ssim** [comment]
I've been looking at this this morning. See #292 .

It seems to me that the inner / outer boundary stuff is what we are supposed to be using now @wkerzendorf , can you confirm? This is what I put up before too:

http://tardis.readthedocs.org/en/latest/examples/profileuniform.html

which uses that approach for ascii files.

I've been checking all the file reading for consistency just now. It seems to me that the current ascii read works ok and that the artis read works ok for abundances and for zoning - however, it seems that the density read is off by 1 index. @aoifeboyle Do you also see that? (I.e. if you check your tardis density grid against the input one, does it seem off by one zone?) Do you know how to write a test - would be good to add one to #292 if we agree that this is now correct!

**Comment by aoifeboyle** [comment]
Hi @ssim . I had a look at your PR and I'm pretty sure you're right. I've made that change and I think everything is working properly now - thanks! I'm not sure how to write a test I'm afraid, but I can look into it over the weekend if you'd like. It's something I want to learn soon anyway. There are a few examples in my current version of the code that I can hopefully learn from.

**Comment by ssim** [comment]
Ok - sounds good. If you manage to write a test that's great - but don't lose too much time on that. If you don't get to it then I'll get Wolfgang to help me with it next week.
