### ISSUE TITLE
Naming conventions in the new plasma

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#328]
@aoifeboyle we need to think about naming conventions in the new plasma class:
There are three different classes:
 1. something with g/cm^3 we call `somethingsomething_density`
 2. somethign with N/cm^3 I would call `somethingsomething_number_density` (what do you think)
 3. And something that is a fraction maybe we want to call `something_something_fraction`? 

This applies to atoms, ions and levels. 

These are just suggestions, we just need to pick one and stick with it. 

What are your thoughts?

**Comment by aoifeboyle** [comment]
Yes, I actually wanted to talk about that! So I tried to be consistent but I had to name `electron_densities` as a plural because that's how it's read in by the montecarlo module and I wanted to interfere with the code outside the plasma as little as possible. Same with `tau_sobolevs`. Then there was the issue that in the old plasma, `level_population` referred to the level number density, while in this plasma it originally referred to the level populations as fractions of the ion populations. I was worried about that causing confusion in the code but it doesn't seem to, so I'll change it back now. Those suggestions you made sound good to me. I think I'll try to change the montecarlo code so I can make all of the parameter names singular, and then I'll go through and correct all the names.

**Comment by wkerzendorf** [comment]
I think it's very good to make these things consistent.

**Comment by wkerzendorf** [comment]
@aoifeboyle please close this issue once you think it has been dealt with.

**Comment by aoifeboyle** [comment]
I've updated everything in my latest PR, except the tau_sobolevs and electron_densities, which are input for the montecarlo stuff. Will look at that soon.
