### ISSUE TITLE
Path problem in case of debian + virtualenv + astropy (debian package)

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#417]
Running into a rather pathological problem when using tardis with the following combination:
- debian Jessie (may apply also to other linux distributions and versions)
- a python virtualenv with --system-site-packages (i.e. rely also on system-wide python packages)
- having only the debian astropy package installed

After setting up the vanilla virtualenv, the python path (as in `sys.path`) looks as expected:

```
/home/ulrich/python-virtualenv/test/lib/python2.7
/home/ulrich/python-virtualenv/test/lib/python2.7/plat-x86_64-linux-gnu
/home/ulrich/python-virtualenv/test/lib/python2.7/lib-tk
/home/ulrich/python-virtualenv/test/lib/python2.7/lib-old
/home/ulrich/python-virtualenv/test/lib/python2.7/lib-dynload
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/home/ulrich/python-virtualenv/test/local/lib/python2.7/site-packages
/home/ulrich/python-virtualenv/test/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gst-0.10
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
```

The virtualenv library paths have precedence over the system-wide paths.

If tardis is now installed inside of this virtualenv, using the setup.py script, the python path gets messed up:

```
/home/ulrich/python-virtualenv/test/local/lib/python2.7/site-packages/tardis_sn-1.0.1-py2.7-linux-x86_64.egg
/usr/lib/python2.7/dist-packages
/home/ulrich/python-virtualenv/test/lib/python2.7/site-packages/tardis_sn-1.0.1-py2.7-linux-x86_64.egg
/home/ulrich/Work/python-modules
/home/ulrich/python-virtualenv/test/lib/python2.7
/home/ulrich/python-virtualenv/test/lib/python2.7/plat-x86_64-linux-gnu
/home/ulrich/python-virtualenv/test/lib/python2.7/lib-tk
/home/ulrich/python-virtualenv/test/lib/python2.7/lib-old
/home/ulrich/python-virtualenv/test/lib/python2.7/lib-dynload
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/home/ulrich/python-virtualenv/test/local/lib/python2.7/site-packages
/home/ulrich/python-virtualenv/test/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gst-0.10
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
```

Now, the system-wide path /usr/bin/python2.7/dist-packages takes precedence over the virtualenv paths. This is due to the file easy_install.pth in the tardis install directory, /home/ulrich/python-virtualenv/test/local/lib/python2.7/site-packages/, which not only adds the tardis egg to the path (which it is supposed to do), but also the global dist-packages path.

This has been confirmed by @tukss, who also identified the cause:

It seems to be connected with the use of the python-setuptools to install/check for astropy. If astropy is not installed in the virtualenv but system-wide through the official debian repositories, the setuptools add the global path to the .pth file and thus to the python path.

**Comment by unoebauer** [comment]
As workaround for this problem, which seems to be caused by using the setuptools wrongly, simply install astropy in the virtualenv, e.g. by

pip install --upgrade astropy

**Comment by tukss** [comment]
This seems to be a general problem with `virtualenv --system-site-packages` and `easy_install` on Debian/Ubuntu.

Just try this in a virtualenv:
```
easy_install numpy
```

This will add `/usr/lib/python2.7/dist-packages` to `easy-install.pth` because it is the path of numpy. Either we have a conceptual problem in understanding setuptools here or it is simply a bug in Debian.

**Comment by tukss** [comment]
This bug affects not only Debian but seemingly any distribution with centrally packaged Python packages. I just tried it on Arch Linux, which uses `/usr/lib/python2.7/site-packages` instead of Debian's `dist-packages`. The error is the same. The global site-packages is added to `easy-install.pth`.

I am wondering if we can somehow prevent the tardis `setup.py` to install astropy as its requirement via setuptools, which triggers this problem. Why is this dependency handled differently from the others (like pandas, etc.)?

**Comment by tukss** [comment]
I found an issue in setuptools that describes similar behavior. In that case it did not cause any trouble but it is still unwanted that already reachable paths are added to `easy-install.pth`. The issue has some suggestions for fixing this in setuptools.

https://bitbucket.org/pypa/setuptools/issues/400/required-package-already-installed

**Comment by wkerzendorf** [comment]
So as far as I understand this - it is a problem in setuptools in debian. So currently there is no fix necessary for tardis, right?

**Comment by tukss** [comment]
Partially. This is a problem with setuptools in general, which is why I linked the setuptools issue. This will happen if you have astropy installed only in your Python install's global `site-packages` and run our `setup.py` in a virtualenv. You will end up with your global `site-packages` early in the `easy-install.pth` of the virtualenv, which is clearly unwanted.

You are right that this is not something that can be fixed in tardis. I hope that setuptools will be fixed at some point. For the time being we should maybe note this behavior somewhere in the tardis docs.

**Comment by wkerzendorf** [comment]
@tukss @unoebauer - thanks for tracking this down. I think a note in the docs is a good idea.

**Comment by unoebauer** [comment]
Did this information propagate into the docs, @wkerzendorf? If so, we could close this issue. Also, @tukss, submitted a patch for this, if I am not mistaken. Status on this?

**Comment by tukss** [comment]
Yes, I patched setuptools to prevent this. It seems one of the Debian patches to accommodate for the dist-packages path was just applied to the wrong section of the file. Unfortunately, my patch wasn't processed yet. I guess the maintainer is pretty busy. If nothing happens until next week, I will ask again.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804281

**Comment by unoebauer** [comment]
@tukss - thanks a lot for staying on top of this. Question still remains whether this issue has already found its way into the docu, @wkerzendorf?

**Comment by wkerzendorf** [comment]
One of the astro people in Debian is @olebole - maybe he has a good connection to this maintainer.

**Comment by unoebauer** [comment]
As mentioned in my first comment, I think that this is quite a pathological use case. Nevertheless, I think we should make a note somewhere on the docu when talking about using astropy in a virtualenv and on debian-based linux distributions.

**Comment by unoebauer** [comment]
Move to documentation TEP (FAQ) section
