### ISSUE TITLE
sum(input packet energy) more than output + absorbed

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#44]
Maybe some doppler factor injection - maybe fixed already.

**Comment by unoebauer** [comment]
@wkerzendorf: Some differences are expected due to expansion work done by radiation field (correct me if I am wrong @ssim). One would have to take one calculation and crunch the numbers to see whether this accounts for everything, but my suspicion is yes. I'd be tempted to close this one. Maybe a note on the documentation would be in order...

**Comment by unoebauer** [comment]
As noted above, adiabatic losses cause this seeming imbalance. Closing this issue.
