### ISSUE TITLE
Missing relativistic CMF-LF frame transformation effects - Overview

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#448]
This issue is an meant to summarise issues #335, #57, #56 and #55 and to collect any other issues concerning omitted relativistic frame transformation effects.

**Comment by unoebauer** [comment]
## Current status:

When transforming between the local co-moving frame (CMF) and the lab frame (LF) only the following effects are taken into account:

- frequency changes due to the Doppler effect 

## Omitted/Neglected effects:

- changes in the propagation direction due to angle aberration (c.f. #57)
- correct transformation of opacity (c.f. #55)
- correct transformation of photon path segments (**needs confirmation**)
- related to everything above: correct frame treatment in Monte Carlo estimators (c.f. #56)

## Tasks:

- decide which of these effects should be implemented
- the documentation should have some notes about which effects are incorporated and which are neglected

**Comment by chvogl** [comment]
@unoebauer 
## Further problems
### Energy conservation in the comoving frame
For each interaction the energy of the packet should be conserved in the comoving frame.
However, at the moment energy conservation is enforced between the comoving energy at the position of the last interaction and the comoving energy at the interaction point.
#### Current approach for energy conservation
#### Step 1
First the comoving energy of the packet is calculated:

    double doppler_factor = move_packet (packet, storage, distance);
    double comov_energy = rpacket_get_energy (packet) * doppler_factor;
Since the return value of move_packet is the doppler factor at the position of the last interaction (or movement across a shell boundary), the value for the comoving energy is also for this point.
#### Step 2
In the next step this comoving energy is transformed back into the lab frame using the inverse doppler factor at the position of the interaction.

    rpacket_set_mu (packet, 2.0 * rk_double (mt_state) - 1.0);
    double inverse_doppler_factor = 1.0 / rpacket_doppler_factor (packet, storage);
    rpacket_set_energy (packet, comov_energy * inverse_doppler_factor);

Therefore, energy conservation is enforced between the comoving energy at the position of the last interaction and the comoving energy at the interaction point.
As a result the current approach retrieves the correct values only asymptotically for an increasing number of shells and/or high optical depths.

**Comment by unoebauer** [comment]
@chvogl, @ssim 

After doing the math, I am fairly convinced that the current interaction scheme is not owed to consistency with the calculation of the Sobolev point:

![sobolev](https://cloud.githubusercontent.com/assets/6351165/13285157/761fd6b4-daf9-11e5-90fd-b572521babf9.jpg)

In other words: since the distance to the Sobolev point only depends on the initial direction and location of the packet on a trajectory segment, it is correct that the C-routine ``compute_distance2line`` uses the corresponding initial Doppler factor. But, there is no reason why the initial Doppler factor should be used in the energy conservation calculation at the interaction point.
