### ISSUE TITLE
'run_tardis' should accept more parameters.

### ISSUE THREAD

**Issue by karandesai-96** [tardis-sn/tardis#524]
- The method `run_tardis` from **tardis/base.py** accepts only two parameters - a tardis config file and an atom data file. While a config can separately specify the filename of abundances and densities profile, the filepath has to be specified as per the user's placement of the files.
- It can also be possible that the user might want to override these and put in custom profiles on same configuration.
- Currently this method does not allow much customization - it should provide more flexibility by offering these parameters.

**Comment by yeganer** [comment]
The `run_tardis` function is a shortcut for exactly the purpose of running a single configuration(yaml or config dict). If one wants more control over the execution of tardis there is always the option of running tardis normally. I suggest you have a look at what `run_tardis` does and mirror the behavior except for the parts where you need other functionality.

As a summary I don't think we want more functionality for `run_tardis` since it's doing what is should and nothing more or less.

**Comment by karandesai-96** [comment]
This point is valid. I feel that there is no need to change `run_tardis`. I am closing this issue.
