### ISSUE TITLE
Certain methods do not accept '~' in OS paths.

### ISSUE THREAD

**Issue by karandesai-96** [tardis-sn/tardis#616]
In certain methods across the modules of _TARDIS_, methods which have a file path as a param, accept only complete absolute paths, such as `/home/username/path/to/file` and passing `~/path/to/file` throws an `OSError`. 

Fix for the issue:
Use `os.path.expandvars(os.path.expanduser(path))`.
#### Probable locations where fix is needed:
- [ ] `AtomData.from_hdf5()` in `tardis.atomic`
- [ ] `run_tardis()` in `tardis.base`
- [ ] `Radial1DModel.to_hdf()` in `tardis.model`

( _constantly updated as occurences are found_ )

**Comment by unoebauer** [comment]
Is this fixed?

**Comment by ftsamis** [comment]
I don't believe this is something to be changed. Implicit tilde path expansion is usual in shells but not in Python [1].

Given that calling `$ tardis ~/tardis_example/tardis_example.yml` from a bash shell works just fine (since the shell does the expansion) I believe that the user should manually do the expansion inside Python if needed.

[1]: For example `open()` throws the same exception.

**Comment by karandesai-96** [comment]
@ftsamis The idea is to make things uniform, then we should remove the exapnsion support from certain methods where it exists.

**Comment by wkerzendorf** [comment]
@karandesai-96 can you write an expandpath/user function and replace all other calls in tardis with that? (the ones that make sense)

**Comment by unoebauer** [comment]
I tend to agree with @ftsamis...

**Comment by unoebauer** [comment]
We'll close this for now, since this is not critical and as @ftsamis pointed out, tilde expansion is the job of the shell and not of python.
