### ISSUE TITLE
spectra resolution

### ISSUE THREAD

**Issue by flyduck2008** [tardis-sn/tardis#683]
Hi ! I am a tardis user. These days I am trying to get sequence of spectra. But I meet two questions. 
1) I think I set enough numbers of packets. (num: 1.e+6 , last_no_of_packets: 1.e+5, no_of_virtual_packets: 10)But the resolution isn't as good as your paper's spectra. Is that anything wrong?
2) I found there is a jump between day 5 and 6. I just change the time. Could you please have a look at  my graph?
Thanks in advance! 

![2016-12-21 9 38 49](https://cloud.githubusercontent.com/assets/20329815/21374378/5523855a-c761-11e6-8c8e-61978f2b92c6.png)

![beta3 3e](https://cloud.githubusercontent.com/assets/20329815/21374358/1e8d4bfc-c761-11e6-930c-428f1f2901a1.png)

**Comment by unoebauer** [comment]
Having looked at the spectra and your config, let me make a few remarks:

* assuming that the only option you changed is the time since explosion, I am not surprised that you see prominent changes in the spectral time series. Since the photosphere will be still at the same velocity, its actual size has increased (R_phot = v_phot * t_exp). The requested luminosity, emerging from the ejecta is also the same. To accommodate this requirement with a larger photosphere, the black-body temperature has to be adjusted. This will of course change the ionisation and excitation balance in the ejecta. As a consequence, variations in the emergent spectra are expected.
* beware of the convergence criteria "specific" in the config file! In older versions of Tardis, this feature was not working properly and a standard update scheme was used instead ("damped" - a simple but quite robust scheme designed to damp out oscillations ). In the current version of Tardis, the "specific" convergence strategy is now used again when specified in the config file. However, I wouldn't recommend using it as it uses very particular update prescriptions which often lead to very bad convergence behaviour. My recommendation: delete the entire converngence part from the config - in this case, Tardis falls back to the robust "damped" treatment.
* You use a reasonable number of packets in the last run. Note, however, that in the Kerzendorf & Sim 2014 paper, sometimes 5 times more packets were used in the final run (5.0e5) and that the spectral were sometimes (always? @wkerzendorf?) filtered with a Savitzky-Golay filter

**Comment by unoebauer** [comment]
I am closing this issue, since it doesn't point to any particular problem in Tardis. Re-open, if you feel otherwise, @flyduck2008
