### ISSUE TITLE
[OpenMP] Use OMP_NUM_THREADS by default

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#699]
If the configuration is missing `montecarlo.nthreads` use the OpenMP default value for parallelization.
On the C level this is already possible by calling `montecarlo_main_loop` with `nthreads=0`.

All that is left to do is change the default value in the yaml schema and verify this is working as expected.

**Comment by saurvs** [comment]
Hello I'm a new contributor here and I'd like to take a stab at this.

**Comment by unoebauer** [comment]
@yeganer -- is this still relevant?

**Comment by unoebauer** [comment]
@yeganer, @wkerzendorf - I just had a look at this issue and came to the following conclusions:

* setting nthreads in the config to 0 triggers the desired behaviour - Tardis OMP uses the number of threads stored in the environment variable ``OMP_NUM_THREADS``
* **However**, if the environment variable is not set, OMP uses all threads available on the system (e.g. on my laptop with an intel i5 and hyperthreading 4). 

Based on these findings, I'd advocate not to change the default value, since it would most likely lead to the undesired outcomes for inexperienced users who have not set ``OMP_NUM_THREADS``. Users with OMP experience who wish to control the Tardis OMP behaviour via an environment variable can still do so by setting nthreads to 1 in their configs.

**Comment by wkerzendorf** [comment]
From my perspective - by default - TARDIS should use the maximum number of threads available. That means the default value should be 0 (not visible in the configuration file), but we should have in our examples nthreads=1 commented out so people see how they can change the number of threads.

**Comment by unoebauer** [comment]
Ok, I think I can live with that. I'll include it in my PR.

**Comment by unoebauer** [comment]
Resolved by #797.
