### ISSUE TITLE
Differences between NLTE calculation results

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#784]
@chvogl Brought to my attention that the NLTE result I obtained last week does not match the spectrum in figure 10 of the KerzendorfSim2014 paper very well near 3000 angstrom. Today's results don't have that problem, however the region between 4000 and 5000 angstrom does not match as well as before.

The goal of this issue is to document this behavior and provide a centralized platform for discussion, especially whether we need to look more closely at the underlying problem.

I believe this might be related to convergence criteria but I haven't confirmed anything yet.
Here are the plots (please note that for some reason the colors are reversed in both plots):

Carsus:
![nlte_carsus](https://user-images.githubusercontent.com/6164110/29669441-bd24adb6-88e3-11e7-865d-0fdea9015c13.png)

Last week after fixing NLTE:
![nlte_verification](https://user-images.githubusercontent.com/6164110/29669442-bd3d8a16-88e3-11e7-92cb-bae944399a9c.png)

**Comment by livnehra** [comment]
Hi,

I'm getting some weird results with NLTE.
I tried to follow the code, and found that in `partition_function.py` the data is prepared in `r_ul_matrix_reshaped`, but then the rates matrix is built using:
`rates_matrix = r_lu_matrix + r_ul_matrix + collision_matrix`
without using `r_ul_matrix_reshaped`.

Am I missing something?

Thanks,
Ran

**Comment by yeganer** [comment]
@livnehra Hey, I'm currently not able to test this but this might be working. If it's a bug or not depends on whether `r_ul_matrix_reshaped` owns the data or not. AFAIK a reshape of a numpy array only create a different view of the same memory location. That means we use the reshape to more easily assign the data but when we use the data to create the `rates_matrix` the original view with the updated data is used (because both views point to the same memory). Please correct me when I'm wrong but I assume that's what's going on.

Nice catch! This part of the code could be written differently to better reflect what is going on. I hope this explanation helped.

**Comment by livnehra** [comment]
@yeganer Hi, of course you are correct and this is not a bug.

After some more digging, I think I may have found the issue - 
I noticed that turning on NLTE for Si II changed the **ion populations** significantly (5x). 
I made sure this was not due to temperature, n_electrons, W or other plausible effects.

Finally I noticed that this is what happens:
1. The NLTE code computes a new `level_boltzmann_factor` for Si II.
2. The `partition_function` for Si II is updated based on these (and always sums to 1.0).
3. The `ion_number_density` is computed based on the new `partition_function`.

I believe that the NLTE treatment was meant to affect only the levels without changing the ionization state. Also, using the Saha equation after messing with the partition function doesn't seem valid...

Thanks!
Ran

**Comment by livnehra** [comment]
So...

Do you think this may be a bug or am I missing something obvious?

Thanks,
Ran

**Comment by livnehra** [comment]
That's exactly what I understood, but I see that turning on NLTE species does change the ionization significantly.

I found that the reason for this is that the partition function is calculated by the NLTE code and then the ionization is erroneously calculated based on this new partition function.

Hoping to get some help to avoid messing with the code myself :)

**Comment by unoebauer** [comment]
Would be good to hear @wkerzendorf's and in particular @yeganer's (who has spent a lot of time fixing NLTE) thoughts on this

**Comment by wkerzendorf** [comment]
@livnehra I think it would be great to get a better insight into your problem. Can we skype or email or something

**Comment by livnehra** [comment]
Of course!

livnehra@gmail.com

Thanks,
Ran

**Comment by livnehra** [comment]
Hi,

After correspondence with @wkerzendorf, I suggest changing [partiton_function.py Line #192](https://github.com/tardis-sn/tardis/blob/4dfe08bcb27a78434ad77c372dced8b0a12db044/tardis/plasma/properties/partition_function.py#L192 ) to

`                general_level_boltzmann_factor[i].ix[species] = level_boltzmann_factor / sum(level_boltzmann_factor) * sum(general_level_boltzmann_factor[i].ix[species])
`

This leaves the partition function as it was.
Sorry I don't have an environment set up to branch and change the code.
Any thoughts?

Thanks,
Ran

**Comment by wkerzendorf** [comment]
@livnehra can you add the same information as you did in the email. @ssim please have a look at it.

**Comment by livnehra** [comment]
Sure,

First I tried:
` general_level_boltzmann_factor[i].ix[species] = level_boltzmann_factor * g[species][0] / level_boltzmann_factor[0]
`

This resulted in:

> 1. Without NLTE:
In [4]: model.plasma.partition_function[1][14]
Out[4]: 
ion_number
0     10.645095
**1      5.818883**
2      1.001149
3      2.000014
4      1.000000
In [3]: model.plasma.ion_number_density[1][14]
Out[3]: 
ion_number
0     1.785938e+00
**1     1.798299e+07**
2     3.462116e+08
3     4.030021e+00
4     1.734323e-15

> 2. With NLTE:
In [5]: model.plasma.partition_function[1][14]
Out[5]: 
ion_number
0     10.636653
**1      2.948737**
2      1.001120
3      2.000014
4      1.000000
In [4]: model.plasma.ion_number_density[1][14]
Out[4]: 
ion_number
0     2.085735e+00
**1     1.015023e+07**
2     3.540443e+08
3     3.537804e+00
4     1.248089e-15


This still changes the ion_number_density drastically, when all we wanted was to change the excitation levels. 

I propose instead:
`general_level_boltzmann_factor[i].ix[species] = level_boltzmann_factor / sum(level_boltzmann_factor) * sum(general_level_boltzmann_factor[i].ix[species])`

This gives:

> 2. With NLTE:
In [2]: model.plasma.partition_function[1][14]
Out[2]: 
ion_number
0     10.637401
**1      5.818222**
2      1.001122
3      2.000014
4      1.000000
In [3]: model.plasma.ion_number_density[1][14]
Out[3]: 
ion_number
0     1.971342e+00
**1     1.916908e+07**
2     3.450255e+08
3     3.528997e+00
4     1.278970e-15

The partition function is very similar.
There is still a small change in the ion_number_density, 
but it may be due to small changes in t_rad and w:
t_rad: 8501 -> 8478 ; w: 0.4317->0.4305

What do you think?

Thanks,
Ran

**Comment by ssim** [comment]
PS. *If* the formula on line 58 is correct (and that is the same "general_level_boltzmann_factor" that we want here), then the equivalent thing we'd want in NLTE would (I think) be

general_level_boltzmann_factor (level_i) = g_0 * n_i / n_0 = Z / N_ion * n_i

...but I don't know if that latex formula in the code is completely correct. (**If** this is correct then I think it might be equivalent to the first suggestion in the post two before this one.)

**Comment by livnehra** [comment]
Perhaps,

But the way the code is implemented, the `ion_number_density` is computed based on the new `partition_function`. According to (my understanding of) the 2014 paper, the NLTE excitation mode is not supposed to (directly) affect the ion populations.

What triggered my examination of this code is that I got a ~4x factor between Si II ion population with and without NLTE.  When I implemented the first suggestion there still remained a factor of almost 2x.

Maybe the solution is only to disconnect the excitation calculation from the ionization calculation when using NLTE?

**Comment by ssim** [comment]
I agree with you that it is somewhat surprising that the NLTE mode changes the partition function by as much as a factor of 2x, but I think it would be good to figure out why that is so - i.e. why is it that the partition function drops so much when the NLTE calculation is active: which levels are depopulating and why?

One could opt to keep the LTE partition functions (e.g. for testing purposes) but I don't think it's physically consistent to use a partition function in the ion calculation that is different from the one implied by the level populations. But it would be good to check for consistency with the calculations in the paper - i.e. compare to the version of the code used then: I think @wkerzendorf knows how to did out that old version for comparison?

**Comment by wkerzendorf** [comment]
@wkerzendorf is in Ghana and will be available next week

**Comment by wkerzendorf** [comment]
@livnehra check out tag v0.9 that should be used as a reference.

**Comment by livnehra** [comment]
Hi,

Glancing at v0.9.2, it seems this was once dealt with directly and not through `level_boltzmann_factor` (in `plasma_array.py`) - without affecting the ion populations.

> for i in xrange(len(self.t_rads)):
      relative_level_populations = np.linalg.solve(rates_matrix[:, :, i], x)
      self.level_populations[i].ix[species] = relative_level_populations * self.ion_populations[i].ix[species]

**Comment by wkerzendorf** [comment]
I think it's easiest to just run it and see what the difference will be.
